theme: jekyll-theme-hacker
title: 혀누 블로그
description: 혀누 공부장
url: https://www.naver.com
author:
  name: [Your name]
  email: [Your email address]
  url: [URL of your website]

paginate: [Number of posts in one paginated section (default: 3)]
owner: [Your name]
year: [Current Year]
